[download_ready]
    subject = "Sequencing run download ready"
    default= """Your download for sequencing runs is available at {{URL}}.

The download file is supposed to be {{SIZE}} bytes in size.
Please check the included sha256 files with sha256sum to verify integrity.

The download will be available at least until {{DELETION_DATE}} which is {{DAYS}} days from now.
(This is independent of the time the run is stored/archived for).

{{#if COMMENT}}
Further comments: %COMMENT%"
{{/if}}
"""
[download_ready.example_data]

      "URL"= "https://example.com/download/123"
      "SIZE"= 123456789
      "DELETION_DATE"= "2023-06-27"
      "DAYS"= 10
      "COMMENT"= "This is an example comment"

[run_completed]
	subject = "Sequencing run completed"
    default = """Your sequencing run {{RUN_NAME}} has been {{#if UPDATE}}updated{{else}}completed{{/if}}.

It will be stored at least until {{DELETION_DATE}} which is {{DAYS}} days from now.

{{#if DOWNLOAD_BEING_PREPARED}}
A download link is currently being prepared and will be sent by seperate email
when it is ready.
{{/if}}
{{#if DO_ARCHIVE}}
After the deletion date, it will be further archived until {{ARCHIVE_UNTIL}}.
The achive will consume {{ARCHIVE_SIZE}} of storage.
{{/if}}
{{#if COMMENTS}}
Further comments: {{COMMENTS}}
{{/if}}
"""

[run_completed.example_data]
      "RUN_NAME"= "230623_NB552003_0218_AHJ3F3BGXT"
      "DELETION_DATE"= "2023-06-27"
      "DAYS"= 10
      "DO_ARCHIVE"= true
	  "ARCHIVE_SIZE" = "0.45 GB"
      "ARCHIVE_UNTIL"= "2033-07-07"
      "COMMENTS"= "This is an example comment."
	  DOWNLOAD_BEING_PREPARED = false
	  UPDATE= false

[run_about_to_be_deleted]
subject = "Sequencing run about to be deleted"
default = """Your sequencing run {{RUN_NAME}} is about to be deleted from the server.

Deletion date: {{DELETION_DATE}} ({{DAYS}} days from now).

{{#if DO_ARCHIVE }}
It will then be archived until {{ARCHIVE_UNTIL}}.
{{else}}
It will not be archived!
Contact us immediately if you need an extension!
{{/if}}
"""

[run_about_to_be_deleted.example_data]
  RUN_NAME= "230623_NB552003_0218_AHJ3F3BGXT"
  DELETION_DATE= "2023-06-27"
  DAYS= 10
  DO_ARCHIVE= true
  ARCHIVE_UNTIL= "2033-07-07"

[run_about_to_be_removed_from_archive]
	subject = "Sequencing run about to be removed from archive"
    default = """
Your sequencing run {RUN_NAME} is about to be deleted from archive.
It will be kept until {{ARCHIVE_UNTIL}}, which is {{DAYS}} days from now.
Please contact the core facilty if you need to download the data (before that date!).
 """
[run_about_to_be_removed_from_archive.example_data]
      "RUN_NAME"= "230623_NB552003_0218_AHJ3F3BGXT"
      "ARCHIVE_UNTIL"= "2033-06-27"
      "DAYS"= 30
