[archive]
value = 3
unit = 'days'

[deletion_delay]
value = 15
unit = 'minutes'

[download_retention]
value = 1
unit = 'days'

[earliest_deletion]
value = 2 
unit = 'days'


[deletion_warning]
value = 1 
unit = 'days'

[archive_deletion_warning]
value = 1 
unit = 'days'
