[archive]
value = 3
unit = 'days'

[deletion_delay]
value = 15
unit = 'minutes'

[download_retention]
value = 30
unit = 'days'

[earliest_deletion]
value = 30 
unit = 'days'


[deletion_warning]
value = 15 
unit = 'days'

[archive_deletion_warning]
value = 31 
unit = 'days'
